version: "3.8"
services:
  app:
    build: .
    container_name: kakeibo-app
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Xmx512m
    command: ["java", "-Xmx512m", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: kakeibo-db
    environment:
      POSTGRES_DB: kakeibo
      POSTGRES_USER: keito
      POSTGRES_PASSWORD: syunkei
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./src/frontend
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  pgdata:
